bpf_doc: Support 1st const parameter of bpf_d_path()
Since commit 1b8abbb12128 ("bpf...d_path(): constify path argument"),
the first parameter of the bpf_d_path() has been changed to a const
constant. We need to modify the header file and bpf_doc.py.

The two error messages are as follows:

    linux/tools/testing/selftests/bpf$ make

      CLNG-BPF [test_progs] bpf_iter_task_vmas.bpf.o
    progs/bpf_iter_task_vmas.c:52:14: error: passing 'const struct path *'
    to parameter of type 'struct path *' discards qualifiers
    [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
       52 |                 bpf_d_path(&file->f_path, d_path_buf, D_PATH_BUF_SIZE);
          |                            ^~~~~~~~~~~~~
    1 error generated.
    ....
    progs/verifier_vfs_accept.c:80:7: error: assigning to 'struct path *'
    from 'const struct path *' discards qualifiers
    [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
       80 |         path = &file->f_path;
          |              ^ ~~~~~~~~~~~~~
    1 error generated.

Fixes: 1b8abbb12128 ("bpf...d_path(): constify path argument")
Signed-off-by: Rong Tao <rongtao@cestc.cn>