docs: target: Convert tcm_mod_builder.py print syntax to python3
Convert the tcm_mod_builder.py file to python3 and fix indentation.

Error:

    $ ./tcm_mod_builder.py
    File "/home/sda/git-repos/linux/Documentation/target/./tcm_mod_builder.py", line 23
        print msg
            ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(msg)?

    $ ./tcm_mod_builder.py
    File "/home/sda/git-repos/linux/Documentation/target/./tcm_mod_builder.py", line 186
        p = open(f, 'w');
    TabError: inconsistent use of tabs and spaces in indentation

Signed-off-by: Rong Tao <rongtao@cestc.cn>