samples/bpf: Fix tracex1: No such file or directory
The __netif_receive_skb_core function can be rename
__netif_receive_skb_core.constprop.0 by gcc
constant propagation optimization and that breaks tracex1.

$ sudo ./tracex1
libbpf: prog 'bpf_prog1': failed to create kprobe '__netif_receive_skb_core+0x0' perf event: No such file or directory
ERROR: bpf_program__attach failed

Signed-off-by: Rong Tao <rongtao@cestc.cn>