docs: trace: Convert decode_msr.py print syntax to python3
Convert the decode_msr.py file to python3 to solve the following running
errors:

    File "Documentation/trace/postprocess/decode_msr.py", line 35
        print j,
             ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean
    print(j, end=" ")?

Signed-off-by: Rong Tao <rongtao@cestc.cn>