samples/bpf: hbm: Fix compile error about fallthrough marking
commit f7a858bffcdd("tools: Rename __fallthrough to fallthrough") rename
macro __fallthrough to fallthrough, commit 4b7ef71ac977("bpftool: Replace
"__fallthrough" by a comment to address merge conflict") use comments to
replace __fallthrough, here we can use fallthrough directly.

Compiling samples/bpf hits an error related to fallthrough marking:
    ...
    CC  samples/bpf/hbm.o
    linux/samples/bpf/hbm.c: In function ‘main’:
    linux/samples/bpf/hbm.c:501:25: error: ‘__fallthrough’ undeclared
    (first use in this function); did you mean ‘fallthrough’?
    501 |                         __fallthrough;
        |                         ^~~~~~~~~~~~~
        |                         fallthrough

Signed-off-by: Rong Tao <rongtao@cestc.cn>