net/ipv4: Fix error: type name requires a specifier or qualifier
since commit 5854a09b4957("net/ipv4: Use __DECLARE_FLEX_ARRAY() helper")
linux/in.h use __DECLARE_FLEX_ARRAY() macro, and sync to tools/ in commit
036b8f5b8970("tools headers uapi: Update linux/in.h copy"), this macro
define in linux/stddef.h, which introduced in commit 3080ea5553cc("stddef:
Introduce DECLARE_FLEX_ARRAY() helper"), thus, stddef.h should be included
in in.h, which resolves the compilation error below:

How to reproduce this compilation error:

$ make -C tools/testing/selftests/bpf/
In file included from progs/bpf_flow.c:8:
linux/in.h:199:3: error: type name requires a specifier or qualifier
                __DECLARE_FLEX_ARRAY(__be32, imsf_slist_flex);
                ^
linux/in.h:199:32: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
                __DECLARE_FLEX_ARRAY(__be32, imsf_slist_flex);
                                             ^
2 errors generated.

Same error occurs with cgroup_skb_sk_lookup_kern.c, connect_force_port4.c,
connect_force_port6.c, etc. that contain the header linux/in.h.

Signed-off-by: Rong Tao <rongtao@cestc.cn>