selftests/bpf: Fix compile error of bin_attribute::read/write()
Since commit 97d06802d10a ("sysfs: constify bin_attribute argument of
bin_attribute::read/write()"), make bin_attribute parameter of
bin_attribute::read/write() const.

    bpf_testmod.c:494:17: error: initialization of ‘ssize_t (*)(struct file *, struct kobject *, const struct bin_attribute *, char *, loff_t,  size_t)’ {aka ‘long int (*)(struct file *, struct kobject *, const struct bin_attribute *, char *, long long int,  long unsigned int)’} from incompatible pointer type ‘ssize_t (*)(struct file *, struct kobject *, struct bin_attribute *, char *, loff_t,  size_t)’ {aka ‘long int (*)(struct file *, struct kobject *, struct bin_attribute *, char *, long long int,  long unsigned int)’} [-Wincompatible-pointer-types]
      494 |         .read = bpf_testmod_test_read,
          |                 ^~~~~~~~~~~~~~~~~~~~~
    bpf_testmod.c:494:17: note: (near initialization for ‘bin_attr_bpf_testmod_file.read’)
    bpf_testmod.c:495:18: error: initialization of ‘ssize_t (*)(struct file *, struct kobject *, const struct bin_attribute *, char *, loff_t,  size_t)’ {aka ‘long int (*)(struct file *, struct kobject *, const struct bin_attribute *, char *, long long int,  long unsigned int)’} from incompatible pointer type ‘ssize_t (*)(struct file *, struct kobject *, struct bin_attribute *, char *, loff_t,  size_t)’ {aka ‘long int (*)(struct file *, struct kobject *, struct bin_attribute *, char *, long long int,  long unsigned int)’} [-Wincompatible-pointer-types]
      495 |         .write = bpf_testmod_test_write,
          |                  ^~~~~~~~~~~~~~~~~~~~~~
    bpf_testmod.c:495:18: note: (near initialization for ‘bin_attr_bpf_testmod_file.write’)
    bpf_testmod.c:589:18: error: initialization of ‘ssize_t (*)(struct file *, struct kobject *, const struct bin_attribute *, char *, loff_t,  size_t)’ {aka ‘long int (*)(struct file *, struct kobject *, const struct bin_attribute *, char *, long long int,  long unsigned int)’} from incompatible pointer type ‘ssize_t (*)(struct file *, struct kobject *, struct bin_attribute *, char *, loff_t,  size_t)’ {aka ‘long int (*)(struct file *, struct kobject *, struct bin_attribute *, char *, long long int,  long unsigned int)’} [-Wincompatible-pointer-types]
      589 |         .write = bpf_testmod_uprobe_write,
          |                  ^~~~~~~~~~~~~~~~~~~~~~~~
    bpf_testmod.c:589:18: note: (near initialization for ‘bin_attr_bpf_testmod_uprobe_file.write’)
    make[5]: *** [/home/rongtao/Git/linux/scripts/Makefile.build:203: bpf_testmod.o] Error 1

Signed-off-by: Rong Tao <rongtao@cestc.cn>